# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 302)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Window = QtWidgets.QFrame(self.centralwidget)
        self.Window.setGeometry(QtCore.QRect(10, 10, 631, 281))
        self.Window.setStyleSheet("QFrame{\n"
"    border-radius: 7px;\n"
"    background-color: #7D5991;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"}")
        self.Window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Window.setObjectName("Window")
        self.WindowFrame = QtWidgets.QFrame(self.Window)
        self.WindowFrame.setGeometry(QtCore.QRect(0, 0, 631, 31))
        self.WindowFrame.setStyleSheet("QFrame{\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color: #946FA6;\n"
"}")
        self.WindowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WindowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WindowFrame.setObjectName("WindowFrame")
        self.CloseWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.CloseWindowButton.setGeometry(QtCore.QRect(591, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CloseWindowButton.setFont(font)
        self.CloseWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #946FA6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #8E68A2;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.CloseWindowButton.setObjectName("CloseWindowButton")
        self.MinimizeWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.MinimizeWindowButton.setGeometry(QtCore.QRect(550, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MinimizeWindowButton.setFont(font)
        self.MinimizeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MinimizeWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #946FA6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #8E68A2;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.MinimizeWindowButton.setDefault(False)
        self.MinimizeWindowButton.setObjectName("MinimizeWindowButton")
        self.AddNewUserCommandButton = QtWidgets.QPushButton(self.Window)
        self.AddNewUserCommandButton.setGeometry(QtCore.QRect(370, 70, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AddNewUserCommandButton.setFont(font)
        self.AddNewUserCommandButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddNewUserCommandButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    background-color: #946FA6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #9A76AB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #8E68A2;\n"
"}")
        self.AddNewUserCommandButton.setObjectName("AddNewUserCommandButton")
        self.UserCommandsListWidget = QtWidgets.QListWidget(self.Window)
        self.UserCommandsListWidget.setGeometry(QtCore.QRect(20, 70, 341, 141))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.UserCommandsListWidget.setFont(font)
        self.UserCommandsListWidget.setTabletTracking(False)
        self.UserCommandsListWidget.setAutoFillBackground(False)
        self.UserCommandsListWidget.setStyleSheet("color: white;\n"
"border-radius: 7px;\n"
"background-color: #946FA6;\n"
"")
        self.UserCommandsListWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UserCommandsListWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.UserCommandsListWidget.setLineWidth(1)
        self.UserCommandsListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.UserCommandsListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.UserCommandsListWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.UserCommandsListWidget.setAutoScroll(True)
        self.UserCommandsListWidget.setTabKeyNavigation(False)
        self.UserCommandsListWidget.setProperty("showDropIndicator", True)
        self.UserCommandsListWidget.setDragDropOverwriteMode(False)
        self.UserCommandsListWidget.setAlternatingRowColors(False)
        self.UserCommandsListWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.UserCommandsListWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.UserCommandsListWidget.setMovement(QtWidgets.QListView.Static)
        self.UserCommandsListWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.UserCommandsListWidget.setProperty("isWrapping", False)
        self.UserCommandsListWidget.setResizeMode(QtWidgets.QListView.Fixed)
        self.UserCommandsListWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.UserCommandsListWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.UserCommandsListWidget.setUniformItemSizes(False)
        self.UserCommandsListWidget.setWordWrap(False)
        self.UserCommandsListWidget.setSelectionRectVisible(False)
        self.UserCommandsListWidget.setObjectName("UserCommandsListWidget")
        self.EditUserCommandButton = QtWidgets.QPushButton(self.Window)
        self.EditUserCommandButton.setGeometry(QtCore.QRect(370, 120, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.EditUserCommandButton.setFont(font)
        self.EditUserCommandButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EditUserCommandButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    background-color: #946FA6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #9A76AB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #8E68A2;\n"
"}")
        self.EditUserCommandButton.setObjectName("EditUserCommandButton")
        self.RemovUserCommandButton = QtWidgets.QPushButton(self.Window)
        self.RemovUserCommandButton.setGeometry(QtCore.QRect(370, 170, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RemovUserCommandButton.setFont(font)
        self.RemovUserCommandButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RemovUserCommandButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    background-color: #946FA6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #9A76AB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #8E68A2;\n"
"}")
        self.RemovUserCommandButton.setObjectName("RemovUserCommandButton")
        self.frame = QtWidgets.QFrame(self.Window)
        self.frame.setGeometry(QtCore.QRect(514, 40, 96, 21))
        self.frame.setStyleSheet("QFrame{\n"
"    border-radius: 0px;\n"
"    background-color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.PortsListComboBox = QtWidgets.QComboBox(self.frame)
        self.PortsListComboBox.setGeometry(QtCore.QRect(0, 0, 96, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.PortsListComboBox.setFont(font)
        self.PortsListComboBox.setStyleSheet("")
        self.PortsListComboBox.setObjectName("PortsListComboBox")
        self.label = QtWidgets.QLabel(self.Window)
        self.label.setGeometry(QtCore.QRect(20, 40, 491, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.OnOrOffProgramButton = QtWidgets.QPushButton(self.Window)
        self.OnOrOffProgramButton.setGeometry(QtCore.QRect(170, 220, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.OnOrOffProgramButton.setFont(font)
        self.OnOrOffProgramButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OnOrOffProgramButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    background-color: #946FA6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #9A76AB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #8E68A2;\n"
"}")
        self.OnOrOffProgramButton.setObjectName("OnOrOffProgramButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CloseWindowButton.setText(_translate("MainWindow", "X"))
        self.MinimizeWindowButton.setText(_translate("MainWindow", "_"))
        self.AddNewUserCommandButton.setText(_translate("MainWindow", "Добавить команду"))
        self.UserCommandsListWidget.setSortingEnabled(False)
        self.EditUserCommandButton.setText(_translate("MainWindow", "Редактировать команду"))
        self.RemovUserCommandButton.setText(_translate("MainWindow", "Удалить команду"))
        self.label.setText(_translate("MainWindow", "Выберите порт к которому подключена Arduino плата:"))
        self.OnOrOffProgramButton.setText(_translate("MainWindow", "Включить программу"))
