# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_command_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(361, 241)
        self.Window = QtWidgets.QFrame(Form)
        self.Window.setGeometry(QtCore.QRect(10, 10, 341, 221))
        self.Window.setStyleSheet("QFrame{\n"
"    border-radius: 7px;\n"
"    background-color: #7D5991;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    background-color: #946FA6;\n"
"}")
        self.Window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Window.setObjectName("Window")
        self.WindowFrame = QtWidgets.QFrame(self.Window)
        self.WindowFrame.setGeometry(QtCore.QRect(0, 0, 341, 31))
        self.WindowFrame.setStyleSheet("QFrame{\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color: #946FA6;\n"
"}")
        self.WindowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WindowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WindowFrame.setObjectName("WindowFrame")
        self.CloseWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.CloseWindowButton.setGeometry(QtCore.QRect(300, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CloseWindowButton.setFont(font)
        self.CloseWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #946FA6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #8E68A2;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.CloseWindowButton.setObjectName("CloseWindowButton")
        self.MinimizeWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.MinimizeWindowButton.setGeometry(QtCore.QRect(259, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MinimizeWindowButton.setFont(font)
        self.MinimizeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MinimizeWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #946FA6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #8E68A2;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.MinimizeWindowButton.setDefault(False)
        self.MinimizeWindowButton.setObjectName("MinimizeWindowButton")
        self.Button = QtWidgets.QPushButton(self.Window)
        self.Button.setGeometry(QtCore.QRect(20, 160, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button.setFont(font)
        self.Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Button.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    background-color: #946FA6;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #9A76AB;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #8E68A2;\n"
"}")
        self.Button.setText("")
        self.Button.setObjectName("Button")
        self.CommandNameLineEdit = QtWidgets.QLineEdit(self.Window)
        self.CommandNameLineEdit.setGeometry(QtCore.QRect(20, 50, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CommandNameLineEdit.setFont(font)
        self.CommandNameLineEdit.setInputMask("")
        self.CommandNameLineEdit.setObjectName("CommandNameLineEdit")
        self.label = QtWidgets.QLabel(self.Window)
        self.label.setGeometry(QtCore.QRect(20, 130, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.Window)
        self.frame.setGeometry(QtCore.QRect(240, 130, 81, 21))
        self.frame.setStyleSheet("QFrame{\n"
"    border-radius: 0px;\n"
"    background-color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ArduinoPortsListComboBox = QtWidgets.QComboBox(self.frame)
        self.ArduinoPortsListComboBox.setGeometry(QtCore.QRect(0, 0, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.ArduinoPortsListComboBox.setFont(font)
        self.ArduinoPortsListComboBox.setObjectName("ArduinoPortsListComboBox")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.ArduinoPortsListComboBox.addItem("")
        self.CommandLineEdit = QtWidgets.QLineEdit(self.Window)
        self.CommandLineEdit.setGeometry(QtCore.QRect(20, 90, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CommandLineEdit.setFont(font)
        self.CommandLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.CommandLineEdit.setInputMask("")
        self.CommandLineEdit.setText("")
        self.CommandLineEdit.setObjectName("CommandLineEdit")
        self.frame.raise_()
        self.WindowFrame.raise_()
        self.Button.raise_()
        self.CommandNameLineEdit.raise_()
        self.label.raise_()
        self.CommandLineEdit.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CloseWindowButton.setText(_translate("Form", "X"))
        self.MinimizeWindowButton.setText(_translate("Form", "_"))
        self.CommandNameLineEdit.setPlaceholderText(_translate("Form", "Придумайте имя команде"))
        self.label.setText(_translate("Form", "Выберите Arduino порт:"))
        self.ArduinoPortsListComboBox.setItemText(0, _translate("Form", "D0"))
        self.ArduinoPortsListComboBox.setItemText(1, _translate("Form", "D1"))
        self.ArduinoPortsListComboBox.setItemText(2, _translate("Form", "D2"))
        self.ArduinoPortsListComboBox.setItemText(3, _translate("Form", "D3"))
        self.ArduinoPortsListComboBox.setItemText(4, _translate("Form", "D4"))
        self.ArduinoPortsListComboBox.setItemText(5, _translate("Form", "D5"))
        self.ArduinoPortsListComboBox.setItemText(6, _translate("Form", "D6"))
        self.ArduinoPortsListComboBox.setItemText(7, _translate("Form", "D7"))
        self.ArduinoPortsListComboBox.setItemText(8, _translate("Form", "D8"))
        self.ArduinoPortsListComboBox.setItemText(9, _translate("Form", "D9"))
        self.ArduinoPortsListComboBox.setItemText(10, _translate("Form", "D10"))
        self.ArduinoPortsListComboBox.setItemText(11, _translate("Form", "D11"))
        self.ArduinoPortsListComboBox.setItemText(12, _translate("Form", "D12"))
        self.ArduinoPortsListComboBox.setItemText(13, _translate("Form", "D13"))
        self.CommandLineEdit.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Для того, чтобы открылся сайт, введите: https://{</span><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">САЙТ</span><span style=\" font-size:10pt; font-weight:600;\">}</span></p><p><span style=\" font-size:10pt; font-weight:600;\">Для того, чтобы открылся файл/приложение, введите путь к нему</span></p></body></html>"))
        self.CommandLineEdit.setPlaceholderText(_translate("Form", "Введите команду"))
